### ISSUE TITLE
the image and video button do not appear on the tool bar

### ISSUE THREAD

**Issue by eastwake** [DiemenDesign/summernote-save-button#1]
followed the instruction but two button are missing even though there are specified in the sample script

['insert',['media','link','hr']],

**Comment by ghost** [comment]
Note sure why you closed this but anyway.
The 'media' part in the toolbar example is a typo. I think I copy and pasted my setup, without realising it was different from what the standard toolbar has. Just make the ['insert'] option the default, or what you want to use, and it should be fine. The 'media' option is for the elFinder plugin that opens the file manager for that plugin.
